/**
 * Google Gemini File Search - Supported File Types
 * Source: https://ai.google.dev/gemini-api/docs/file-search#supported-files
 */

/**
 * Maximum file size allowed by Google File Search API
 */
export const MAX_FILE_SIZE = 100 * 1024 * 1024; // 100MB

const APPLICATION_MIME_TYPES = [
  'application/dart',
  'application/ecmascript',
  'application/json',
  'application/ms-java',
  'application/msword',
  'application/pdf',
  'application/sql',
  'application/typescript',
  'application/vnd.curl',
  'application/vnd.dart',
  'application/vnd.ibm.secure-container',
  'application/vnd.jupyter',
  'application/vnd.ms-excel',
  'application/vnd.oasis.opendocument.text',
  'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
  'application/x-csh',
  'application/x-hwp',
  'application/x-hwp-v5',
  'application/x-latex',
  'application/x-php',
  'application/x-powershell',
  'application/x-sh',
  'application/x-shellscript',
  'application/x-tex',
  'application/x-zsh',
  'application/xml',
  'application/zip',
] as const;

const TEXT_MIME_TYPES = [
  'text/1d-interleaved-parityfec',
  'text/RED',
  'text/SGML',
  'text/cache-manifest',
  'text/calendar',
  'text/cql',
  'text/cql-extension',
  'text/cql-identifier',
  'text/css',
  'text/csv',
  'text/csv-schema',
  'text/dns',
  'text/encaprtp',
  'text/enriched',
  'text/example',
  'text/fhirpath',
  'text/flexfec',
  'text/fwdred',
  'text/gff3',
  'text/grammar-ref-list',
  'text/hl7v2',
  'text/html',
  'text/javascript',
  'text/jcr-cnd',
  'text/jsx',
  'text/markdown',
  'text/mizar',
  'text/n3',
  'text/parameters',
  'text/parityfec',
  'text/php',
  'text/plain',
  'text/provenance-notation',
  'text/prs.fallenstein.rst',
  'text/prs.lines.tag',
  'text/prs.prop.logic',
  'text/raptorfec',
  'text/rfc822-headers',
  'text/rtf',
  'text/rtp-enc-aescm128',
  'text/rtploopback',
  'text/rtx',
  'text/sgml',
  'text/shaclc',
  'text/shex',
  'text/spdx',
  'text/strings',
  'text/t140',
  'text/tab-separated-values',
  'text/texmacs',
  'text/troff',
  'text/tsv',
  'text/tsx',
  'text/turtle',
  'text/ulpfec',
  'text/uri-list',
  'text/vcard',
  'text/vnd.DMClientScript',
  'text/vnd.IPTC.NITF',
  'text/vnd.IPTC.NewsML',
  'text/vnd.a',
  'text/vnd.abc',
  'text/vnd.ascii-art',
  'text/vnd.curl',
  'text/vnd.debian.copyright',
  'text/vnd.dvb.subtitle',
  'text/vnd.esmertec.theme-descriptor',
  'text/vnd.exchangeable',
  'text/vnd.familysearch.gedcom',
  'text/vnd.ficlab.flt',
  'text/vnd.fly',
  'text/vnd.fmi.flexstor',
  'text/vnd.gml',
  'text/vnd.graphviz',
  'text/vnd.hans',
  'text/vnd.hgl',
  'text/vnd.in3d.3dml',
  'text/vnd.in3d.spot',
  'text/vnd.latex-z',
  'text/vnd.motorola.reflex',
  'text/vnd.ms-mediapackage',
  'text/vnd.net2phone.commcenter.command',
  'text/vnd.radisys.msml-basic-layout',
  'text/vnd.senx.warpscript',
  'text/vnd.sosi',
  'text/vnd.sun.j2me.app-descriptor',
  'text/vnd.trolltech.linguist',
  'text/vnd.wap.si',
  'text/vnd.wap.sl',
  'text/vnd.wap.wml',
  'text/vnd.wap.wmlscript',
  'text/vtt',
  'text/wgsl',
  'text/x-asm',
  'text/x-bibtex',
  'text/x-boo',
  'text/x-c',
  'text/x-c++hdr',
  'text/x-c++src',
  'text/x-cassandra',
  'text/x-chdr',
  'text/x-coffeescript',
  'text/x-component',
  'text/x-csh',
  'text/x-csharp',
  'text/x-csrc',
  'text/x-cuda',
  'text/x-d',
  'text/x-diff',
  'text/x-dsrc',
  'text/x-emacs-lisp',
  'text/x-erlang',
  'text/x-gff3',
  'text/x-go',
  'text/x-haskell',
  'text/x-java',
  'text/x-java-properties',
  'text/x-java-source',
  'text/x-kotlin',
  'text/x-lilypond',
  'text/x-lisp',
  'text/x-literate-haskell',
  'text/x-lua',
  'text/x-moc',
  'text/x-objcsrc',
  'text/x-pascal',
  'text/x-pcs-gcd',
  'text/x-perl',
  'text/x-perl-script',
  'text/x-python',
  'text/x-python-script',
  'text/x-r-markdown',
  'text/x-rsrc',
  'text/x-rst',
  'text/x-ruby-script',
  'text/x-rust',
  'text/x-sass',
  'text/x-scala',
  'text/x-scheme',
  'text/x-script.python',
  'text/x-scss',
  'text/x-setext',
  'text/x-sfv',
  'text/x-sh',
  'text/x-siesta',
  'text/x-sos',
  'text/x-sql',
  'text/x-swift',
  'text/x-tcl',
  'text/x-tex',
  'text/x-vbasic',
  'text/x-vcalendar',
  'text/xml',
  'text/xml-dtd',
  'text/xml-external-parsed-entity',
  'text/yaml',
] as const;

export const SUPPORTED_MIME_TYPES = [...APPLICATION_MIME_TYPES, ...TEXT_MIME_TYPES] as const;

export type SupportedMimeType = (typeof SUPPORTED_MIME_TYPES)[number];

/**
 * Maps file extensions to their corresponding MIME types
 * Based on Google Gemini File Search API supported formats
 */
const EXTENSION_TO_MIME_TYPE: Record<string, string> = {
  // Application types
  '.pdf': 'application/pdf',
  '.doc': 'application/msword',
  '.docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  '.xls': 'application/vnd.ms-excel',
  '.xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  '.ppt': 'application/vnd.ms-powerpoint',
  '.pptx': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  '.odt': 'application/vnd.oasis.opendocument.text',
  '.json': 'application/json',
  '.xml': 'application/xml',
  '.zip': 'application/zip',
  '.sql': 'application/sql',
  '.tex': 'application/x-latex',
  '.php': 'application/x-php',
  '.sh': 'application/x-sh',
  '.dart': 'application/dart',

  // Text types - Common programming languages
  '.txt': 'text/plain',
  '.md': 'text/markdown',
  '.markdown': 'text/markdown',
  '.html': 'text/html',
  '.htm': 'text/html',
  '.css': 'text/css',
  '.js': 'text/javascript',
  '.mjs': 'text/javascript',
  '.jsx': 'text/jsx',
  '.ts': 'text/typescript',
  '.tsx': 'text/tsx',
  '.csv': 'text/csv',
  '.tsv': 'text/tab-separated-values',
  '.rtf': 'text/rtf',
  '.yaml': 'text/yaml',
  '.yml': 'text/yaml',

  // Programming languages
  '.py': 'text/x-python',
  '.java': 'text/x-java',
  '.c': 'text/x-c',
  '.cpp': 'text/x-c++src',
  '.h': 'text/x-chdr',
  '.hpp': 'text/x-c++hdr',
  '.cs': 'text/x-csharp',
  '.go': 'text/x-go',
  '.rs': 'text/x-rust',
  '.rb': 'text/x-ruby-script',
  '.swift': 'text/x-swift',
  '.kt': 'text/x-kotlin',
  '.scala': 'text/x-scala',
  '.r': 'text/x-r-markdown',
};

/**
 * Gets the MIME type for a file based on its extension
 * Returns 'application/octet-stream' for unknown file types
 */
export function getContentTypeByExtension(filePath: string): string {
  const ext = filePath.substring(filePath.lastIndexOf('.')).toLowerCase();
  return EXTENSION_TO_MIME_TYPE[ext] || 'application/octet-stream';
}
